# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - Tuner

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ci-tuner.yml'
      - 'tuner/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-tuner.yml'
      - 'tuner/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: '3.10.12'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tuner/requirements-dev.txt

      - name: Install tuner dependencies
        run: |
          pip install -r tuner/requirements-tuner.txt
          pip install -r requirements-iree-unpinned.txt

      - name: Run tuner tests
        run: pytest tuner/

      - name: Run mypy type checker
        run: mypy tuner/tuner
